### Importing Neccessary Libraries

In [1]:
import pandas as pd
import numpy as np

### Extraction Layer

In [2]:
path = r'dataset\raw_data\yinc_ecommerce.csv'
yinc_df = pd.read_csv(path)

In [3]:
yinc_df.head()
yinc_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   str
 1   Customer_ID         1000 non-null   str
 2   Customer_Name       1000 non-null   str
 3   Product_ID          1020 non-null   str
 4   Product_Name        1020 non-null   str
 5   Brand               1020 non-null   str
 6   Category            1020 non-null   str
 7   Price               1020 non-null   float64
 8   Quantity            1020 non-null   int64
 9   Total_Price         1020 non-null   float64
 10  Order_Date          1020 non-null   str
 11  Shipping_Address    1020 non-null   str
 12  City                1020 non-null   str
 13  State               1019 non-null   str
 14  Country             1020 non-null   str
 15  Postal_Code         1020 non-null   int64
 16  Email               1020 non-null   str
 17  Phone_Number        1020 non-null   str
 18  Payment_Method      1020 non-null   str
 19  Transaction_Status  1020 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 159.5 KB

In [4]:
yinc_df.isnull().sum()

Order_ID              20
Customer_ID           20
Customer_Name         20
Product_ID             0
Product_Name           0
Brand                  0
Category               0
Price                  0
Quantity               0
Total_Price            0
Order_Date             0
Shipping_Address       0
City                   0
State                  1
Country                0
Postal_Code            0
Email                  0
Phone_Number           0
Payment_Method         0
Transaction_Status     0
dtype: int64

In [5]:
yinc_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='str')

### Data Cleaning and Transformation

In [6]:
# Drop Missing Values 
yinc_df.dropna(subset=['Order_ID','Customer_ID', 'Customer_Name', 'State'], inplace=True)

In [7]:
yinc_df.isnull().sum()

Order_ID              0
Customer_ID           0
Customer_Name         0
Product_ID            0
Product_Name          0
Brand                 0
Category              0
Price                 0
Quantity              0
Total_Price           0
Order_Date            0
Shipping_Address      0
City                  0
State                 0
Country               0
Postal_Code           0
Email                 0
Phone_Number          0
Payment_Method        0
Transaction_Status    0
dtype: int64

In [8]:
# Convert Ordr_date from String to Datetime object
yinc_df['Order_Date'] = pd.to_datetime(
    yinc_df['Order_Date'],
    format="%d/%m/%Y %H:%M",
    errors='coerce'
)

In [9]:
# Sanity Check
yinc_df['Order_Date'].head()

2   2020-03-06 06:49:00
3   2020-07-31 07:09:00
4   2021-05-11 04:33:00
5   2023-09-12 01:47:00
6   2021-08-20 18:02:00
Name: Order_Date, dtype: datetime64[us]

### Create Tables

In [10]:
# Customer Table
customer_df = yinc_df[['Customer_ID','Customer_Name', 'Email', 'Phone_Number']].drop_duplicates().reset_index(drop=True).copy()
customer_df.head()

,Customer_ID,Customer_Name,Email,Phone_Number
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,Dominic Buchanan,margaret97@example.com,259.603.6134
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,Daniel Allen,angela55@example.com,+1-869-659-4272x982
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,Daniel Schmidt,wayne59@example.org,292.840.0975x724
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,John Gonzalez,qsherman@example.com,+1-643-561-3912x262
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,Amber Benitez,derek85@example.com,3424148376

In [11]:
# Product Table
product_df = yinc_df[['Product_ID', 'Product_Name', 'Brand', 'Category', 'Price' ]].drop_duplicates().reset_index(drop=True).copy()
product_df.head()

,Product_ID,Product_Name,Brand,Category,Price
0,2ef6e8fa-6a36-4515-b1c2-a0a700abf386,despite,"Lawson, Stone and Campos",perfume oil,250.57
1,3ba38e01-f8e7-4af2-9246-87ef0961d4f5,sea,Washington Group,perfume oil,179.81
2,a58c53bd-a34b-4541-b926-bec9eb84cac2,suddenly,Rodgers Ltd,perfume oil,600.55
3,e6021be5-90be-4199-b6c6-82542fb2973c,site,"Wilson, Scott and Johnson",perfume oil,414.36
4,60127671-ab32-4fb5-bfeb-1a7782ad835e,act,"Riddle, Alvarez and Robinson",perfume,704.05

In [12]:
# Shipping Table
shipping_df = yinc_df[['Customer_ID', 'Shipping_Address','City', 'State', 'Country', 'Postal_Code']].drop_duplicates().reset_index(drop=True).copy()

shipping_df.index.name = 'Shipping_ID'
shipping_df = shipping_df.reset_index()

shipping_df.head()

,Shipping_ID,Customer_ID,Shipping_Address,City,State,Country,Postal_Code
0,0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,"PSC 2224, Box 2284\nAPO AP 65880",Jordanborough,Arkansas,Kuwait,27879
1,1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,"83909 Johnson Mall\nTranberg, MS 99017",Lake Ginatown,Georgia,Saint Vincent and the Grenadines,39336
2,2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,"82101 Johnson Flat\nWest Ryan, MS 29075",Sarahville,Ohio,France,30845
3,3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,"4542 Gary Lane\nSouth Alexander, VI 27671",Lake Michelle,Arkansas,Sao Tome and Principe,30955
4,4,81b513ad-5c02-48cf-bff0-39e1440c4d22,"6794 Caroline Crescent\nEast Karlside, GU 81379",Olsenville,Mississippi,Croatia,45429

In [13]:
# Order Table
order_df = yinc_df[['Order_ID', 'Customer_ID','Product_ID', 'Quantity', 'Total_Price', 'Order_Date']].drop_duplicates().reset_index(drop=True).copy()
order_df.head()

,Order_ID,Customer_ID,Product_ID,Quantity,Total_Price,Order_Date
0,e32af09a-b6ab-497e-af3a-331e4d4ed6e7,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,2ef6e8fa-6a36-4515-b1c2-a0a700abf386,2,501.14,2020-03-06 06:49:00
1,86eb8859-14ab-4d4e-9267-c5826f4e0c8e,fa3ca35a-5540-404b-a7eb-9001cdcbd840,3ba38e01-f8e7-4af2-9246-87ef0961d4f5,6,1078.86,2020-07-31 07:09:00
2,7379b560-8897-4623-92a2-523ddcdc43a1,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,a58c53bd-a34b-4541-b926-bec9eb84cac2,7,4203.85,2021-05-11 04:33:00
3,30c57f86-2fed-43c0-a399-654c2c3bb18d,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,e6021be5-90be-4199-b6c6-82542fb2973c,9,3729.24,2023-09-12 01:47:00
4,41c29d81-9622-43c1-b537-7cdb320d3e6a,81b513ad-5c02-48cf-bff0-39e1440c4d22,60127671-ab32-4fb5-bfeb-1a7782ad835e,9,6336.45,2021-08-20 18:02:00

In [14]:
# Payment Method Table
payment_method_df = yinc_df[['Order_ID','Payment_Method','Transaction_Status']].drop_duplicates().reset_index(drop=True).copy()
payment_method_df.head()

                               Order_ID Payment_Method Transaction_Status
0  e32af09a-b6ab-497e-af3a-331e4d4ed6e7     Debit Card          completed
1  86eb8859-14ab-4d4e-9267-c5826f4e0c8e    Credit Card          completed
2  7379b560-8897-4623-92a2-523ddcdc43a1         PayPal            pending
3  30c57f86-2fed-43c0-a399-654c2c3bb18d         PayPal          completed
4  41c29d81-9622-43c1-b537-7cdb320d3e6a         PayPal            pending

In [15]:
# Save Table to CSV
customer_df.to_csv(r'dataset/cleaned_data/customer.csv', index=False)
product_df.to_csv(r'dataset/cleaned_data/product.csv', index=False)
shipping_df.to_csv(r'dataset/cleaned_data/shipping.csv', index=False)
order_df.to_csv(r'dataset/cleaned_data/order.csv', index=False)
payment_method_df.to_csv(r'dataset/cleaned_data/payment_method.csv', index=False)

In [19]:
yinc_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='str')