### Importing Neccessary Libraries

In [76]:
import pandas as pd
import numpy as np

### Extraction Layer

In [77]:
path = r'dataset\raw_data\yinc_ecommerce.csv'
yinc_df = pd.read_csv(path)

In [78]:
yinc_df.head()
yinc_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   str
 1   Customer_ID         1000 non-null   str
 2   Customer_Name       1000 non-null   str
 3   Product_ID          1020 non-null   str
 4   Product_Name        1020 non-null   str
 5   Brand               1020 non-null   str
 6   Category            1020 non-null   str
 7   Price               1020 non-null   float64
 8   Quantity            1020 non-null   int64
 9   Total_Price         1020 non-null   float64
 10  Order_Date          1020 non-null   str
 11  Shipping_Address    1020 non-null   str
 12  City                1020 non-null   str
 13  State               1019 non-null   str
 14  Country             1020 non-null   str
 15  Postal_Code         1020 non-null   int64
 16  Email               1020 non-null   str
 17  Phone_Number        1020 non-null   str
 18  Payment_Method      1020 non-null   str
 19  Transaction_Status  1020 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 159.5 KB

In [79]:
#Cleaning Columns
yinc_df.columns = (
    yinc_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [80]:
yinc_df.columns

Index(['order_id', 'customer_id', 'customer_name', 'product_id',
       'product_name', 'brand', 'category', 'price', 'quantity', 'total_price',
       'order_date', 'shipping_address', 'city', 'state', 'country',
       'postal_code', 'email', 'phone_number', 'payment_method',
       'transaction_status'],
      dtype='str')

In [81]:
yinc_df.isnull().sum()

order_id              20
customer_id           20
customer_name         20
product_id             0
product_name           0
brand                  0
category               0
price                  0
quantity               0
total_price            0
order_date             0
shipping_address       0
city                   0
state                  1
country                0
postal_code            0
email                  0
phone_number           0
payment_method         0
transaction_status     0
dtype: int64

### Data Cleaning and Transformation

In [82]:
# Drop Missing Values 
yinc_df = yinc_df.dropna(subset=['order_id', 'customer_id', 'customer_name', 'state'])

In [83]:
# Clean order_date datatype (Str - DateTime Object)
yinc_df['order_date'] = pd.to_datetime(yinc_df['order_date'], format = "%d/%m/%Y %H:%M", errors='coerce')

# Sanity Check
yinc_df['order_date'].head()

2   2020-03-06 06:49:00
3   2020-07-31 07:09:00
4   2021-05-11 04:33:00
5   2023-09-12 01:47:00
6   2021-08-20 18:02:00
Name: order_date, dtype: datetime64[us]

In [84]:
yinc_df.isnull().sum()

order_id              0
customer_id           0
customer_name         0
product_id            0
product_name          0
brand                 0
category              0
price                 0
quantity              0
total_price           0
order_date            0
shipping_address      0
city                  0
state                 0
country               0
postal_code           0
email                 0
phone_number          0
payment_method        0
transaction_status    0
dtype: int64

### Create Tables

In [85]:
# Customer Table
customer_df = yinc_df[['customer_id','customer_name', 'email', 'phone_number']].drop_duplicates().reset_index(drop=True).copy()
customer_df.head()

,customer_id,customer_name,email,phone_number
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,Dominic Buchanan,margaret97@example.com,259.603.6134
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,Daniel Allen,angela55@example.com,+1-869-659-4272x982
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,Daniel Schmidt,wayne59@example.org,292.840.0975x724
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,John Gonzalez,qsherman@example.com,+1-643-561-3912x262
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,Amber Benitez,derek85@example.com,3424148376

In [86]:
# Delete and create a new Email Address Column to Customer Table
del[customer_df["email"]]
customer_df['email_address'] = (
    customer_df['customer_name']
    .str.lower()
    .str.strip()
    .str.replace(" ","_")
    + '@'
    + customer_df['customer_id']
    + '.com'
    )
customer_df.head()

,customer_id,customer_name,phone_number,email_address
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,Dominic Buchanan,259.603.6134,dominic_buchanan@e0d6cb3c-c4b0-4cfe-8225-b65d0...
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,Daniel Allen,+1-869-659-4272x982,daniel_allen@fa3ca35a-5540-404b-a7eb-9001cdcbd...
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,Daniel Schmidt,292.840.0975x724,daniel_schmidt@7ad4de53-e6d7-4cd3-99b8-13fb70f...
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,John Gonzalez,+1-643-561-3912x262,john_gonzalez@4b9b409c-19f2-41c0-bc7c-6556e064...
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,Amber Benitez,3424148376,amber_benitez@81b513ad-5c02-48cf-bff0-39e1440c...

In [87]:
# Product Table
product_df = yinc_df[['product_id', 'product_name', 'brand', 'category', 'price' ]].drop_duplicates().reset_index(drop=True).copy()
product_df.head()

,product_id,product_name,brand,category,price
0,2ef6e8fa-6a36-4515-b1c2-a0a700abf386,despite,"Lawson, Stone and Campos",perfume oil,250.57
1,3ba38e01-f8e7-4af2-9246-87ef0961d4f5,sea,Washington Group,perfume oil,179.81
2,a58c53bd-a34b-4541-b926-bec9eb84cac2,suddenly,Rodgers Ltd,perfume oil,600.55
3,e6021be5-90be-4199-b6c6-82542fb2973c,site,"Wilson, Scott and Johnson",perfume oil,414.36
4,60127671-ab32-4fb5-bfeb-1a7782ad835e,act,"Riddle, Alvarez and Robinson",perfume,704.05

In [88]:
# Shipping Table
shipping_df = yinc_df[['customer_id', 'shipping_address','city', 'state', 'country', 'postal_code']].drop_duplicates().reset_index(drop=True).copy()

shipping_df.index.name = 'shipping_id'
shipping_df = shipping_df.reset_index()

shipping_df.head()

,shipping_id,customer_id,shipping_address,city,state,country,postal_code
0,0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,"PSC 2224, Box 2284\nAPO AP 65880",Jordanborough,Arkansas,Kuwait,27879
1,1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,"83909 Johnson Mall\nTranberg, MS 99017",Lake Ginatown,Georgia,Saint Vincent and the Grenadines,39336
2,2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,"82101 Johnson Flat\nWest Ryan, MS 29075",Sarahville,Ohio,France,30845
3,3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,"4542 Gary Lane\nSouth Alexander, VI 27671",Lake Michelle,Arkansas,Sao Tome and Principe,30955
4,4,81b513ad-5c02-48cf-bff0-39e1440c4d22,"6794 Caroline Crescent\nEast Karlside, GU 81379",Olsenville,Mississippi,Croatia,45429

In [89]:
# Order Table
order_df = yinc_df[['order_id', 'customer_id','product_id', 'quantity', 'total_price', 'order_date']].drop_duplicates().reset_index(drop=True).copy()
order_df.head()

,order_id,customer_id,product_id,quantity,total_price,order_date
0,e32af09a-b6ab-497e-af3a-331e4d4ed6e7,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,2ef6e8fa-6a36-4515-b1c2-a0a700abf386,2,501.14,2020-03-06 06:49:00
1,86eb8859-14ab-4d4e-9267-c5826f4e0c8e,fa3ca35a-5540-404b-a7eb-9001cdcbd840,3ba38e01-f8e7-4af2-9246-87ef0961d4f5,6,1078.86,2020-07-31 07:09:00
2,7379b560-8897-4623-92a2-523ddcdc43a1,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,a58c53bd-a34b-4541-b926-bec9eb84cac2,7,4203.85,2021-05-11 04:33:00
3,30c57f86-2fed-43c0-a399-654c2c3bb18d,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,e6021be5-90be-4199-b6c6-82542fb2973c,9,3729.24,2023-09-12 01:47:00
4,41c29d81-9622-43c1-b537-7cdb320d3e6a,81b513ad-5c02-48cf-bff0-39e1440c4d22,60127671-ab32-4fb5-bfeb-1a7782ad835e,9,6336.45,2021-08-20 18:02:00

In [90]:
# Payment Method Table
payment_method_df = yinc_df[['order_id','payment_method','transaction_status']].drop_duplicates().reset_index(drop=True).copy()
payment_method_df.head()

                               order_id payment_method transaction_status
0  e32af09a-b6ab-497e-af3a-331e4d4ed6e7     Debit Card          completed
1  86eb8859-14ab-4d4e-9267-c5826f4e0c8e    Credit Card          completed
2  7379b560-8897-4623-92a2-523ddcdc43a1         PayPal            pending
3  30c57f86-2fed-43c0-a399-654c2c3bb18d         PayPal          completed
4  41c29d81-9622-43c1-b537-7cdb320d3e6a         PayPal            pending

### Save Tables to CSV in Cleaned Data Folder

In [91]:
# Save Table to CSV
customer_df.to_csv(r'dataset/cleaned_data/customer.csv', index=False)
product_df.to_csv(r'dataset/cleaned_data/product.csv', index=False)
shipping_df.to_csv(r'dataset/cleaned_data/shipping.csv', index=False)
order_df.to_csv(r'dataset/cleaned_data/order.csv', index=False)
payment_method_df.to_csv(r'dataset/cleaned_data/payment_method.csv', index=False)

In [92]:
yinc_df.columns

Index(['order_id', 'customer_id', 'customer_name', 'product_id',
       'product_name', 'brand', 'category', 'price', 'quantity', 'total_price',
       'order_date', 'shipping_address', 'city', 'state', 'country',
       'postal_code', 'email', 'phone_number', 'payment_method',
       'transaction_status'],
      dtype='str')

### Database Connection / Loading

In [93]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in c:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.9.11)

In [94]:
import psycopg2

In [95]:
def get_db_connection():
    connection = psycopg2.connect(
        user = 'postgres',
        password = 'Yomi554860',
        host = 'localhost',
        port = 5432,
        database = 'yinc_e_commerce'
    )
    return connection

In [96]:
conn = get_db_connection()

### Creating SQL Table Queries

In [97]:
def create_tables():
    conn = get_db_connection()
    cursor = conn.cursor()
    create_table_query = '''
                            CREATE SCHEMA IF NOT EXISTS yinc;
                            
                            DROP TABLE IF EXISTS yinc.customer CASCADE;
                            DROP TABLE IF EXISTS yinc.product  CASCADE;
                            DROP TABLE IF EXISTS yinc.shipping CASCADE;
                            DROP TABLE IF EXISTS yinc.order CASCADE;
                            DROP TABLE IF EXISTS yinc.payment_method CASCADE;
                            
                            CREATE TABLE IF NOT EXISTS yinc.customer (
                                customer_id    UUID PRIMARY KEY,
                                customer_name  TEXT,
                                phone_number   TEXT,
                                email_address  TEXT
                            );
                            
                             CREATE TABLE IF NOT EXISTS yinc.product (
                                product_id     UUID PRIMARY KEY,
                                product_name   TEXT,
                                brand          TEXT,
                                category       TEXT,
                                price          FLOAT
                            );
                            
                            CREATE TABLE IF NOT EXISTS yinc.shipping (
                                shipping_id              INT PRIMARY KEY,
                                customer_id              UUID,
                                shipping_address         TEXT,
                                city                     TEXT,
                                state                    TEXT,
                                country                  TEXT,
                                postal_code              INT,
                                FOREIGN KEY (customer_id) REFERENCES yinc.customer(customer_id)    
                            );
                            
                              CREATE TABLE IF NOT EXISTS yinc.order (
                                order_id                 UUID PRIMARY KEY,
                                customer_id              UUID,
                                product_id               UUID,
                                quantity                 INT,
                                total_price              NUMERIC(10,2),
                                order_date               DATE,
                                FOREIGN KEY (customer_id) REFERENCES yinc.customer(customer_id), 
                                FOREIGN KEY (product_id) REFERENCES yinc.product(product_id)   
                            );
                            
                             CREATE TABLE IF NOT EXISTS yinc.payment_method (
                                order_id                 UUID, 
                                payment_method           TEXT,
                                transaction_status       TEXT,
                                FOREIGN KEY (order_id) REFERENCES yinc.order(order_id)    
                            );'''
    
    try:
        cursor.execute(create_table_query)
        conn.commit()

    except Exception as e:
        print("Error:", e)
        conn.rollback()

    finally:
        cursor.close()
        conn.close()

In [98]:
print("Creating Table")
create_tables()
print("Table Query Created...........")

Creating Table

Table Query Created...........

### Loading CSV Files to Postgres

In [99]:
import csv
def load_data_from_csv(csv_path):
    conn = get_db_connection()
    cursor = conn.cursor()
    with open(csv_path, "r") as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yinc.customer (customer_id, customer_name, phone_number, email_address)
                           VALUES (%s, %s, %s, %s);''',
                           row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_file_path = r'dataset\cleaned_data\customer.csv'

load_data_from_csv(csv_file_path)

In [100]:
import csv
def load_data_from_csv(csv_path):
    conn = get_db_connection()
    cursor = conn.cursor()
    with open(csv_path, "r") as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yinc.product (product_id, product_name, brand, category, price)
                           VALUES (%s, %s, %s, %s, %s);''',
                           row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_file_path = r'dataset\cleaned_data\product.csv'

load_data_from_csv(csv_file_path)

In [101]:
import csv
def load_data_from_csv(csv_path):
    conn = get_db_connection()
    cursor = conn.cursor()
    with open(csv_path, "r") as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yinc.shipping (shipping_id, customer_id, shipping_address, city, state, country, postal_code)
                           VALUES (%s, %s, %s, %s, %s, %s, %s);''',
                           row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_file_path = r'dataset\cleaned_data\shipping.csv'

load_data_from_csv(csv_file_path)

In [102]:
import csv
def load_data_from_csv(csv_path):
    conn = get_db_connection()
    cursor = conn.cursor()
    with open(csv_path, "r") as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yinc.order (order_id, customer_id, product_id, quantity, total_price, order_date)
                           VALUES (%s, %s, %s, %s, %s, %s);''',
                           row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_file_path = r'dataset\cleaned_data\order.csv'

load_data_from_csv(csv_file_path)

In [103]:
import csv
def load_data_from_csv(csv_path):
    conn = get_db_connection()
    cursor = conn.cursor()
    with open(csv_path, "r") as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yinc.payment_method (order_id, payment_method, transaction_status)
                           VALUES (%s, %s, %s);''',
                           row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_file_path = r'dataset\cleaned_data\payment_method.csv'

load_data_from_csv(csv_file_path)